# Generated by Django 5.2.6 on 2025-10-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioenv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='waveType',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='preset',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
